src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="string", length=128) */
    private $title;

    /** @ORM\Column(type="text", nullable=true) */
    private $description;

    /** @ORM\Column(type="text", nullable=true) */
    private $followUp;

    /** @ORM\Column(type="boolean") */
    private $public;

    /** @ORM\Column(type="string", length=128) */
    private $priority;

    /** @ORM\Column(type="string", length=128) */
    private $status;

    /** @ORM\Column(type="simple_array", nullable=true) */
    private $tags;

    /** @ORM\Column(type="date", nullable=true) */
    private $targetCompleteDate;

    /** @ORM\Column(type="string", length=255, nullable=true) */
    private $document;

    /** @ORM\ManyToMany(targetEntity="App\Entity\User") */
    private $userSubscribed;

    /** @ORM\ManyToOne(targetEntity="App\Entity\User") */
    private $userCreated;

    /** @ORM\ManyToOne(targetEntity="App\Entity\User") */
    private $userUpdated;

    /** @ORM\Column(type="datetime") */
    private $dateCreated;

    /** @ORM\Column(type="datetime") */
    private $dateUpdated;

    public function __construct()
    {
        $this->userSubscribed = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getTitle() ?? '';
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getFollowUp(): ?string
    {
        return $this->followUp;
    }

    public function setFollowUp(?string $followUp): self
    {
        $this->followUp = $followUp;
        return $this;
    }

    /** @return Collection|User[] */
    public function getUserSubscribed(): Collection
    {
        return $this->userSubscribed;
    }

    public function setUserSubscribed(array $users): self
    {
        $this->userSubscribed = $users;
        return $this;
    }

    public function getPublic(): bool
    {
        return $this->public;
    }

    public function getPublicString(): string
    {
        return $this->public ? 'Yes' : 'No';
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;
        return $this;
    }

    public function getPriority(): string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): self
    {
        $this->priority = $priority;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getTags(): array
    {
        return $this->tags;
    }

    public function getTagsString(): ?string
    {
        return empty($this->tags) ? null : implode(', ', $this->tags);
    }

    public function setTags(array $tags): self
    {
        $this->tags = $tags;
        return $this;
    }

    public function getTargetCompleteDate(): ?\DateTime
    {
        return $this->targetCompleteDate;
    }

    public function getTargetCompleteDateString(): ?string
    {
        return $this->getTargetCompleteDate() === null ? null : $this->getTargetCompleteDate()->format('Y-m-d');
    }

    public function getDaysToTargetCompleteDate(): ?int
    {
        if ($this->targetCompleteDate === null){
            return null;
        }

        $diff = (new \DateTime('today'))->diff($this->targetCompleteDate);

        if ($diff->invert === 1){
            return $diff->days * -1;
        }

        return $diff->days;
    }

    public function setTargetCompleteDate(?\DateTime $targetCompleteDate): self
    {
        $this->targetCompleteDate = $targetCompleteDate;
        return $this;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(?string $document): self
    {
        $this->document = $document;
        return $this;
    }

    public function getUserCreated(): User
    {
        return $this->userCreated;
    }

    public function setUserCreated(User $userCreated): self
    {
        $this->userCreated = $userCreated;
        return $this;
    }

    public function getUserUpdated(): User
    {
        return $this->userUpdated;
    }

    public function setUserUpdated(User $userUpdated): self
    {
        $this->userUpdated = $userUpdated;
        return $this;
    }

    public function getDateCreated(): \DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function getDateCreatedString(): string
    {
        return $this->getDateCreated()->format('Y-m-d @ h:i a');
    }

    /**
     * @ORM\PrePersist()
     * @return Task
     */
    public function setDateCreated(): self
    {
        $this->dateCreated = new \DateTime();
        return $this;
    }

    public function getDateUpdated(): \DateTimeInterface
    {
        return $this->dateUpdated;
    }

    public function getDateUpdatedString(): string
    {
        return $this->getDateUpdated()->format('Y-m-d @ h:i a');
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @return Task
     */
    public function setDateUpdated(): self
    {
        $this->dateUpdated = new \DateTime();
        return $this;
    }

    // only needed for jermbundle CRUD delete method
    public function getFile(): void{}
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Form\User\UserData;
use App\Form\User\UserUpdateData;
use Doctrine\ORM\Mapping as ORM;
use Musicjerm\Bundle\JermBundle\Entity\User as BaseUser;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $username;

    /**
     * @ORM\Column(type="string", length=128)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=64)
     */
    protected $password;

    /**
     * @ORM\Column(type="simple_array")
     */
    protected $roles;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $lastName;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $profilePic;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreated;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateUpdated;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="user_created")
     */
    private $userCreated;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="user_updated")
     */
    private $userUpdated;

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->profilePic;
    }

    public function setProfilePic(?string $profilePic): self
    {
        $this->profilePic = $profilePic;
        return $this;
    }

    public function getDateCreated(): \DateTimeInterface
    {
        return $this->dateCreated;
    }

    /**
     * @ORM\PrePersist()
     * @return User
     */
    public function setDateCreated(): self
    {
        $this->dateCreated = new \DateTime();

        return $this;
    }

    public function getDateUpdated(): \DateTimeInterface
    {
        return $this->dateUpdated;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @return User
     */
    public function setDateUpdated(): self
    {
        $this->dateUpdated = new \DateTime();

        return $this;
    }

    public function getUserCreated(): ?self
    {
        return $this->userCreated;
    }

    public function setUserCreated(?self $userCreated): self
    {
        $this->userCreated = $userCreated;

        return $this;
    }

    public function getUserUpdated(): ?self
    {
        return $this->userUpdated;
    }

    public function setUserUpdated(?self $userUpdated): self
    {
        $this->userUpdated = $userUpdated;

        return $this;
    }

    public function getDateCreatedString(): string
    {
        return $this->getDateCreated()->format('Y-m-d @ h:i:s a');
    }

    public function getDateUpdatedString(): string
    {
        return $this->getDateUpdated()->format('Y-m-d @ h:i:s a');
    }

    /** @param UserData|UserUpdateData $dto */
    public function setDataFromDTO($dto): void
    {
        $this->username = $dto->username;
        $this->email = $dto->email;
        $this->firstName = $dto->firstName;
        $this->lastName = $dto->lastName;
        $dto->password === null ?: $this->password = password_hash($dto->password, PASSWORD_BCRYPT);
        $this->roles = [$dto->roles];
        $this->isActive = $dto->isActive;
        $dto->profilePic === null ?: $this->profilePic = $this->getId() . '.' . $dto->profilePic->guessExtension();
    }
}

src/Form/Task/TaskCreateType.php
<?php

namespace App\Form\Task;

use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class TaskCreateType extends AbstractType
{
    /** @var User */
    private $user;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        if ($tokenStorage->getToken() !== null){
            $this->user = $tokenStorage->getToken()->getUser();
        }
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description', TextareaType::class, array(
                'required' => false
            ))
            ->add('public', CheckboxType::class, ['required' => false])
            ->add('userGroups', EntityType::class, array(
                'class' => \App\Entity\UserGroup::class,
                'query_builder' => function(EntityRepository $er){
                    return $er->createQueryBuilder('ug')
                        ->where('ug.userCreated = :user')
                        ->setParameter('user', $this->user);
                },
                'multiple' => true,
                'required' => false,
                'attr' => ['class' => 'select2', 'style' => 'width: 100%']
            ))
            ->add('priority', ChoiceType::class, array(
                'choices' => array(
                    'Minor' => 'Minor',
                    'Major' => 'Major',
                    'Critical' => 'Critical'
                )
            ))
            ->add('targetCompleteDate', DateType::class, array(
                'label' => 'Target Completion Date',
                'required' => false,
                'html5' => false,
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker']
            ))
            ->add('tags', null, array(
                'label' => 'Tags / Categories (Comma Separated)'
            ))
            ->add('document');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(array(
            'data_class' => TaskData::class,
        ));
    }
}

src/Form/Task/TaskData.php
<?php

namespace App\Form\Task;

use App\Entity\User;
use App\Entity\UserGroup;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

class TaskData
{
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\Length(max="128")
     */
    public $title;

    /** @var string */
    public $description;

    /** @var string */
    public $followUp;

    /** @var ArrayCollection|UserGroup[] */
    public $userGroups;

    /** @var ArrayCollection|User[] */
    public $subbedUsers;

    /** @var boolean */
    public $public;

    /**
     * @var string
     * @Assert\NotBlank()
     */
    public $priority;

    /**
     * @var string
     */
    public $status;

    /** @var \DateTime */
    public $targetCompleteDate;

    /**
     * @var string
     *@Assert\Length(max="128")
     */
    public $tags;

    /**
     * @var UploadedFile
     * @Assert\File(maxSize="50M")
     */
    public $document;
}

src/Form/Task/TaskTransformer.php
<?php

namespace App\Form\Task;

use App\Entity\Task;
use App\Entity\User;
use Doctrine\Common\Collections\Collection;

class TaskTransformer
{
    /** @var \App\Entity\User */
    private $user;

    public function __construct($user)
    {
        $this->user = $user;
    }

    public function transform(TaskData $taskData, Task $task = null): Task
    {
        // create new task if none passed, set values
        if ($task === null){
            $task = new Task();
            $task->setUserCreated($this->user);
        }

        // set new values
        $task->setTitle($taskData->title);
        $task->setDescription($taskData->description);
        $task->setFollowUp($taskData->followUp);
        $task->setPublic($taskData->public);
        $task->setPriority($taskData->priority);
        $task->setStatus($taskData->status ?? 'New');
        $task->setTargetCompleteDate($taskData->targetCompleteDate);

        // if user groups selected, subscribe users to task
        if ($taskData->userGroups !== null){
            /** @var Collection|User[] $userArray */
            $userArray = array($this->user);
            foreach ($taskData->userGroups as $userGroup){
                /** @var \App\Entity\User $user */
                foreach ($userGroup->getUsers() as $user){
                    \in_array($user, $userArray, true) ?: $userArray[] = $user;
                }
            }
            $task->setUserSubscribed($userArray);
        }

        // if tag string set, create and set array
        if ($taskData->tags !== null){
            $tagArray = array();
            foreach (\explode(',', $taskData->tags) as $tag){
                trim($tag) === '' ?: $tagArray[] = trim($tag);
            }
            $task->setTags($tagArray);
        }

        // set user updated
        $task->setUserUpdated($this->user);

        // set file name if document uploaded
        if ($taskData->document !== null){
            $task->setDocument($taskData->document->getClientOriginalName());
        }

        // return task
        return $task;
    }

    public function reverseTransform(Task $task): TaskData
    {
        // create new task data from queried object
        $taskData = new TaskData();
        $taskData->title = $task->getTitle();
        $taskData->description = $task->getDescription();
        $taskData->followUp = $task->getFollowUp();
        $taskData->subbedUsers = $task->getUserSubscribed();
        $taskData->public = $task->getPublic();
        $taskData->priority = $task->getPriority();
        $taskData->status = $task->getStatus();
        $taskData->targetCompleteDate = $task->getTargetCompleteDate();
        $taskData->tags = implode(', ', $task->getTags());

        // return task data
        return $taskData;
    }
}

templates/task/update_task.html.twig
{% extends '@Jerm/Modal/form.html.twig' %}

{% block form %}
    {{ form_row(form.title) }}
    {{ form_row(form.description) }}
    {{ form_row(form.followUp) }}
    {{ form_row(form.public) }}
    {{ form_row(form.subbedUsers) }}
    <div class="row">
        <div class="col-xs-12 col-sm-6">{{ form_row(form.priority) }}</div>
        <div class="col-xs-12 col-sm-6">{{ form_row(form.status) }}</div>
    </div>
    {{ form_row(form.targetCompleteDate) }}
    {{ form_row(form.tags) }}
    {{ form_row(form.document) }}
{% endblock %}

templates/task/view_task.html.twig
{% extends '@Jerm/Modal/blank.html.twig' %}

{% block content %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        <h4 class="modal-title">
            Task #{{ task.id }}

            {% if editable %}
                <a class="btn btn-sm modal_redirect" data-href="{{ path('update_task', { 'id': task.id }) }}">
                    <i class="fa fa-pencil"></i> Edit
                </a>
            {% endif %}

            {% if subscribed %}
                <a class="btn btn-sm modal_redirect"
                   data-href="{{ path('subscribe_task', { 'id': task.id }) }}">
                    <i class="fa fa-check-square-o"></i> Subscribed
                </a>
            {% else %}
                <a class="btn btn-sm modal_redirect"
                   data-href="{{ path('subscribe_task', { 'id': task.id }) }}">
                    <i class="fa fa-square-o"></i> Subscribe
                </a>
            {% endif %}

            <a class="btn btn-sm modal_redirect" data-href="{{ path('view_task', { 'id': task.id }) }}">
                <i class="fa fa-refresh"></i> Refresh
            </a>
        </h4>

        <small class="label label-{{ attribute(status_class, task.status) }}">{{ task.status }}</small>

        {% if task.public %}
            <small class="label label-success">Public</small>
        {% endif %}

        {% for tag in task.tags %}
            <small class="label label-default">{{ tag }}</small>
        {% endfor %}
    </div>

    <div class="modal-body">
        <div class="row">
            <div class="col-xs-12 col-sm-6 user-block">
                {% if task.userCreated.profilePic is not null %}
                    <img class="img-circle" src="{{ asset('app/img/userProfile/' ~ task.userCreated.profilePic) }}">
                {% else %}
                    <img class="img-circle" src="{{ asset('bundles/jerm/img/avatar.gif') }}">
                {% endif %}
                <span class="username">{{ task.userCreated.fullName }}</span>
                <span class="description">Created on {{ task.dateCreatedString }}</span>
            </div>

            <div class="col-xs-12 col-sm-6">
                {% if task.document is not null %}
                    <a class="pull-right" href="{{ path('jerm_bundle_get_file', { 'entity': 'task', 'id': task.id }) }}">
                        <i class="fa fa-download"></i> {{ task.document }}
                    </a>
                    {% if editable %}
                        <br>
                        <a class="btn btn-sm text-red pull-right modal_redirect_confirm"
                           data-href="{{ path('task_delete_doc', { 'id': task.id }) }}"
                           data-message="Are you sure you want to remove {{ task.document }}">
                            <i class="fa fa-times-circle"></i> Remove
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="modal-body">
        <h4 class="modal-title">{{ task.title }}</h4>

        {% if task.description %}<p class="text">{{ task.description|raw|nl2br }}</p>{% endif %}

        {% if task.followUp %}
            <div class="panel panel-{{ attribute(status_class, task.status) }}">
                <div class="panel-body">{{ task.followUp|raw|nl2br }}</div>
            </div>
        {% endif %}

        {% if target_diff_string is not null %}
            <p class="text-{{ target_diff_class }}">
                <i class="fa fa-{{ target_diff_icon }}"></i>
                {{ target_diff_string }} ({{ task.targetCompleteDateString }})
            </p>
        {% endif %}

        {% if task.dateCreated != task.dateUpdated %}
            <p class="text-muted">Last updated by {{ task.userUpdated.fullName }} on {{ task.dateUpdatedString }}</p>
        {% endif %}
    </div>

    <div id="note_view">
        {{ render(controller('App\\Controller\\NoteController::createAction', {
            'entity': 'App:Task'|url_encode,
            'id': task.id,
            'lock': lock_notes
        })) }}
    </div>

    <div class="modal-footer">
        <button class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('app/js/task_view.js') }}"></script>
{% endblock %}